services:
  job:
    build: .
    container_name: azure-container-apps-poc
    environment:
      - STORAGE_ACCOUNT_NAME=${STORAGE_ACCOUNT_NAME}
      - STORAGE_CONTAINER_NAME=${STORAGE_CONTAINER_NAME}

      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}

      - STORAGE_CONFIG_FILE_PATH=${STORAGE_CONFIG_FILE_PATH}
      
